name: Deploy to GitHub Pages via angular-cli-ghpages
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Run latest-tag
      uses: EndBug/latest-tag@latest
      with:
        ref: latest
        description: currently deployed version

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Prepare and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm run ng -- deploy --base-href=/DSA-Tools/ --name="Klajan" --email="48261494+Klajan@users.noreply.github.com" --no-silent
